### ISSUE TITLE
cuDNN error

### ISSUE THREAD

**Issue by Barthold-Albrecht** [dailenson/SDT#25]
Running inference with the pre-trained model on a VM (Tesla K80) gives RuntimeError: cuDNN error: CUDNN_STATUS_ARCH_MISMATCH. I set up the env with your requirements. Do you have any hints on what might go wrong here?

**Comment by dailenson** [comment]
Could you please provide your complete pytorch environment, like cuda, cuDNN, pytorch version? I guess your incorrect cuDNN version causes this error.

**Comment by Barthold-Albrecht** [comment]
Thx for getting back. Issue is solved. You were right, setting cuda=11.8 did the trick.
